### ISSUE TITLE
syntax highlighting: URL underlining scope

### ISSUE THREAD

**Issue by chreliot** [flyx/TeX.novaextension#1]
In URLs like

```
\url{https://one2three} 
\href{https://one2three}  
```

underlining extends from the `https` through the `one` but then stops there.

(I am very pleased to see this Nova extension available — thank you!)

**Comment by flyx** [comment]
This seems to happen because `2` is highlighted as a number and therefore breaks Nova's URL detection. Currently, `\url` `\href` etc are not specifically recognized by the grammar. There are two possible ways to fix your issue:

 * recognize URL-carrying commands and disable number highlighting there
 * disable number highlighting outside math mode if number is without unit (em/ex/cm etc).

The second option seems to be the better one since the current feature of number highlighting hits a high number of false positives (any decimal digit in text basically). However `2em` in an URL will then still stop URL recognition, so ideally both tasks should be implemented.

I'll look into this in the coming days.

**Comment by chreliot** [comment]
Alternatively, you could just disable number highlighting completely? Or, disable it outside math mode?

I am not used to seeing number highlighting, but perhaps it is useful in some way for you/others.

**Comment by flyx** [comment]
This has been fixed in c706eb130c92c65c840a32e5d5986e2cb131123f. I decided to disable number highlighting outside math mode altogether. New version has been published that contains this fix.
