### ISSUE TITLE
TeX Suite v1.0.2 keeps crashing on Nova 9.3

### ISSUE THREAD

**Issue by ghost** [flyx/TeX.novaextension#11]
Ever since I upgraded Nova 9.1 to 9.3 and TeX Suite from 0.5.1 to 1.0.2, TeX Suite has been crashing when I enabled it. The only error showing up is:

```
Extension Service Quit Unexpectedly 

An issue with one or more extensions caused the service to terminate. As a result, all extensions will need to reload.

The following extensions were executing when the crash occurred:
• TeX Suite (org.flyx.tex)
```

Is this related to [this](https://devforum.nova.app/t/nova-crashes-when-deactivating-my-extension/1468) issue?

**Comment by flyx** [comment]
No, the linked issue crashes Nova itself and doesn't occur for me anymore since I implemented a workaround. Your issue is something different. Could you please give the following info:

 * Whether each of `latexmk`, `context`, `texlab` and `digestif` is available on your login shell, and if so their versions.
 * Version of macOS.
 * Steps to reproduce the error (an important info is whether you need to have any workspace with `.tex` files open or not).
 * Check whether the crash occurs with LaTeX, ConTeXt or both disabled in your workspace settings. If the extension crashes immediately after loading a workspace with `.tex` files, you can disable these options by putting the following into `.nova/Configuration.json`:
 
```json
{
      "org.flyx.tex.context.enable" : false,
      "org.flyx.tex.latex.enable" : false
}
```

I just updated to Nova 9.3 and I see that the language server isn't working anymore, but I'm not seeing a crash. This might be a Nova issue. did you have 1.0.2 running under Nova 9.1 before you updated?

PS: It might be a few days before I can look at this in detail. The Panic folks must be optimistic by not only releasing on a Friday, but also right before easter weekend…

**Comment by flyx** [comment]
Had a look at this and found a bug in the JS code. Please update to 1.0.3 and report back if you see this problem still happening. If it does, please give the information requested in my previous comment, since I cannot reproduce this.

**Comment by flyx** [comment]
Closing due to lack of feedback, assuming this is fixed since I can't reproduce.
