### ISSUE TITLE
feature request: italic and bold commands

### ISSUE THREAD

**Issue by chreliot** [flyx/TeX.novaextension#3]
A useful addition would be wrapping selected text in italics or bold commands with a shortcut, e.g.,

- ⌘i wraps selected text in `\emph{}`
- ⌘b wraps selected text in `\textbf{}`

**Comment by flyx** [comment]
I'm wondering whether `\emph{}` should actually be bound to ⌘i since its behavior is a bit more complex than *italicize the text*. OTOH, using `\emph{}` is more often than not a better option than `\textit{}`.

Is this a feature commonly found elsewhere? I'm asking mainly to know what users might expect, also regarding the shortcuts.

**Comment by chreliot** [comment]
This would parallel Nova's behavior for Markdown texts (I _think_ built-in rather than from an extension). In an `.md` file, **⌘i** produces `*text*` and  **⌘b** produces `**text**`.

For LaTeX in particular, this behavior I described would replicate that of the LaTeX bundle in TextMate, and the behavior of at least the popular LaTeX extensions I've tried in Atom and VS Code. So, I think it's safe to suggest it's standard.

**Comment by flyx** [comment]
Great, I'll see to include this in the next release.

**Comment by flyx** [comment]
I implemented this on <kbd>⌘⇧i</kbd> and <kbd>⌘⇧b</kbd> since <kbd>⌘i</kbd> is bound to *File->Actions->Get Info* and <kbd>⌘b</kbd> is *Project->Build*. You can of course modify the shortcuts in your Nova preferences, I just thought it wouldn't be wise to override existing shortcuts, less so since the extension does provide a *build* action.

New version will hit the registry later.
